# Generated by Django 5.0.6 on 2024-05-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
